import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { PerfectScrollbarModule } from 'ngx-perfect-scrollbar';
import {
  MatAutocompleteModule,
  MatBadgeModule,
  MatBottomSheetModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatNativeDateModule,
  MatLineModule,
  MatOptionModule,
  MatRippleModule,
  MatPseudoCheckboxModule,
  MatDatepickerModule,
  MatDialogModule,
  MatDividerModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  MatSelectModule,
  MatSidenavModule,
  MatSlideToggleModule,
  MatSliderModule,
  MatSnackBarModule,
  MatSortModule,
  MatStepperModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatTreeModule,
  MatPaginatorIntl,
  MAT_SNACK_BAR_DEFAULT_OPTIONS
} from '@angular/material';
import { FlexLayoutModule } from '@angular/flex-layout';
import { ConfirmMessageComponent } from './components/confirm-message/confirm-message.component';
import { PipeModule } from './pipes/pipe.module';
import { MatPaginatorIntlCustom } from './services/paginator-custom-intl.service';
import { InfoMessageComponent } from './components/info-message/info-message.component';
import { MessageComponent } from './components/message/message.component';
import { AlertMessageComponent } from './components/alert-message/alert-message.component';
import { UpperCaseDirective } from './directives/upper-case.directive';
import { PdfViewerComponent } from './components/pdf-viewer/pdf-viewer.component';
import { NgxExtendedPdfViewerModule } from 'ngx-extended-pdf-viewer';
import { ResponsiveRowsDirective } from './directives/responsive-rows.directive';

@NgModule({
  imports: [
    ReactiveFormsModule,
    PerfectScrollbarModule,
    HttpClientModule,
    FormsModule,
    FlexLayoutModule,
    PipeModule,
  

    // MATERIAL
    MatAutocompleteModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatNativeDateModule,
    MatLineModule,
    MatOptionModule,
    MatRippleModule,
    MatPseudoCheckboxModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatTreeModule,
    NgxExtendedPdfViewerModule,
    MatChipsModule,
  ],
  exports: [
    ReactiveFormsModule,
    PerfectScrollbarModule,
    HttpClientModule,
    FormsModule,
    FlexLayoutModule,
    PipeModule,
    UpperCaseDirective,
    ResponsiveRowsDirective,

    // MATERIAL
    MatAutocompleteModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatNativeDateModule,
    MatLineModule,
    MatOptionModule,
    MatRippleModule,
    MatPseudoCheckboxModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatTreeModule,
    NgxExtendedPdfViewerModule,
    MatChipsModule,
  ],
  declarations: [
    ConfirmMessageComponent,
    InfoMessageComponent,
    MessageComponent,
    AlertMessageComponent,
    UpperCaseDirective,
    ResponsiveRowsDirective,
    PdfViewerComponent
  ],
  entryComponents: [
    ConfirmMessageComponent,
    InfoMessageComponent,
    MessageComponent,
    AlertMessageComponent,
    PdfViewerComponent
  ],
  providers: [
    { provide: MatPaginatorIntl, useClass: MatPaginatorIntlCustom },
    { provide: MAT_SNACK_BAR_DEFAULT_OPTIONS, useValue: { duration: 3000, verticalPosition: 'top', horizontalPosition: 'right' } },
  ]
})
export class SharedModule {}
